build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bookworm"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bookworm"
  i386: "ghcr.io/home-assistant/i386-base-debian:bookworm"
labels:
  org.opencontainers.image.title: "Snowflake Proxy for Home Assistant"
  org.opencontainers.image.description: "Help people in censored countries access the Internet."
codenotary: true
codenotary.signer: "hobby@c14h19no2.nl"
